/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExecutiveCredential {
  'username' : string,
  'password' : string,
  'name' : string,
}
export interface ProfitRecord {
  'id' : string,
  'customerName' : string,
  'isDailyTargetSet' : boolean,
  'dailyTarget' : number,
  'date' : string,
  'createdAt' : bigint,
  'executiveName' : string,
  'executiveUsername' : string,
  'amountReceived' : number,
}
export interface UserProfile {
  'username' : string,
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExecutive' : ActorMethod<[string, string, string], undefined>,
  'addProfitRecordAsAdmin' : ActorMethod<
    [string, string, string, number, number, string, string],
    undefined
  >,
  'addProfitRecordAsExecutive' : ActorMethod<
    [string, string, string, number, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateAdmin' : ActorMethod<[string, string], string>,
  'authenticateExecutive' : ActorMethod<[string, string], string>,
  'changeAdminPassword' : ActorMethod<[string], undefined>,
  'changeExecutivePassword' : ActorMethod<[string, string], undefined>,
  'deleteExecutive' : ActorMethod<[string], undefined>,
  'deleteProfitRecord' : ActorMethod<[string], undefined>,
  'getAllExecutives' : ActorMethod<[], Array<[ExecutiveCredential, bigint]>>,
  'getAllProfitRecords' : ActorMethod<[], Array<ProfitRecord>>,
  'getAnnualProfitRecords' : ActorMethod<[string], Array<ProfitRecord>>,
  'getAnnualProfitRecordsByExecutive' : ActorMethod<
    [string, string],
    Array<ProfitRecord>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExecutive' : ActorMethod<[string], ExecutiveCredential>,
  'getExecutiveName' : ActorMethod<[string], string>,
  'getMonthlyProfitRecords' : ActorMethod<[string], Array<ProfitRecord>>,
  'getMonthlyProfitRecordsByExecutive' : ActorMethod<
    [string, string],
    Array<ProfitRecord>
  >,
  'getProfitRecordsForExecutive' : ActorMethod<[string], Array<ProfitRecord>>,
  'getRecordsByDay' : ActorMethod<[string], Array<ProfitRecord>>,
  'getRecordsByExecutiveByDay' : ActorMethod<
    [string, string],
    Array<ProfitRecord>
  >,
  'getRecordsSortedByAmountReceived' : ActorMethod<[], Array<ProfitRecord>>,
  'getRecordsSortedByDailyTarget' : ActorMethod<[], Array<ProfitRecord>>,
  'getRecordsSortedByDate' : ActorMethod<[], Array<ProfitRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminMode' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];