/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExecutiveCredential = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
});
export const ProfitRecord = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'isDailyTargetSet' : IDL.Bool,
  'dailyTarget' : IDL.Float64,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'executiveName' : IDL.Text,
  'executiveUsername' : IDL.Text,
  'amountReceived' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExecutive' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addProfitRecordAsAdmin' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addProfitRecordAsExecutive' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'authenticateExecutive' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'changeAdminPassword' : IDL.Func([IDL.Text], [], []),
  'changeExecutivePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteExecutive' : IDL.Func([IDL.Text], [], []),
  'deleteProfitRecord' : IDL.Func([IDL.Text], [], []),
  'getAllExecutives' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ExecutiveCredential, IDL.Int))],
      ['query'],
    ),
  'getAllProfitRecords' : IDL.Func([], [IDL.Vec(ProfitRecord)], ['query']),
  'getAnnualProfitRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'getAnnualProfitRecordsByExecutive' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExecutive' : IDL.Func([IDL.Text], [ExecutiveCredential], ['query']),
  'getExecutiveName' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMonthlyProfitRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'getMonthlyProfitRecordsByExecutive' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'getProfitRecordsForExecutive' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'getRecordsByDay' : IDL.Func([IDL.Text], [IDL.Vec(ProfitRecord)], ['query']),
  'getRecordsByExecutiveByDay' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'getRecordsSortedByAmountReceived' : IDL.Func(
      [],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'getRecordsSortedByDailyTarget' : IDL.Func(
      [],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'getRecordsSortedByDate' : IDL.Func([], [IDL.Vec(ProfitRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminMode' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExecutiveCredential = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
  });
  const ProfitRecord = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'isDailyTargetSet' : IDL.Bool,
    'dailyTarget' : IDL.Float64,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'executiveName' : IDL.Text,
    'executiveUsername' : IDL.Text,
    'amountReceived' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExecutive' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addProfitRecordAsAdmin' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addProfitRecordAsExecutive' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'authenticateExecutive' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'changeAdminPassword' : IDL.Func([IDL.Text], [], []),
    'changeExecutivePassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteExecutive' : IDL.Func([IDL.Text], [], []),
    'deleteProfitRecord' : IDL.Func([IDL.Text], [], []),
    'getAllExecutives' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ExecutiveCredential, IDL.Int))],
        ['query'],
      ),
    'getAllProfitRecords' : IDL.Func([], [IDL.Vec(ProfitRecord)], ['query']),
    'getAnnualProfitRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getAnnualProfitRecordsByExecutive' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExecutive' : IDL.Func([IDL.Text], [ExecutiveCredential], ['query']),
    'getExecutiveName' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMonthlyProfitRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getMonthlyProfitRecordsByExecutive' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getProfitRecordsForExecutive' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getRecordsByDay' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getRecordsByExecutiveByDay' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getRecordsSortedByAmountReceived' : IDL.Func(
        [],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getRecordsSortedByDailyTarget' : IDL.Func(
        [],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'getRecordsSortedByDate' : IDL.Func([], [IDL.Vec(ProfitRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminMode' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };