/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExecutiveCredential {
    username: string;
    password: string;
    name: string;
}
export interface UserProfile {
    username: string;
    name: string;
    role: string;
}
export interface ProfitRecord {
    id: string;
    customerName: string;
    isDailyTargetSet: boolean;
    dailyTarget: number;
    date: string;
    createdAt: bigint;
    executiveName: string;
    executiveUsername: string;
    amountReceived: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addExecutive(name: string, username: string, password: string): Promise<void>;
    addProfitRecordAsAdmin(id: string, date: string, customerName: string, amountReceived: number, dailyTarget: number, executiveName: string, executiveUsername: string): Promise<void>;
    addProfitRecordAsExecutive(id: string, date: string, customerName: string, amountReceived: number, executiveName: string, executiveUsername: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticateAdmin(username: string, password: string): Promise<string>;
    authenticateExecutive(username: string, password: string): Promise<string>;
    changeAdminPassword(newPassword: string): Promise<void>;
    changeExecutivePassword(username: string, newPassword: string): Promise<void>;
    deleteExecutive(username: string): Promise<void>;
    deleteProfitRecord(id: string): Promise<void>;
    getAllExecutives(): Promise<Array<[ExecutiveCredential, bigint]>>;
    getAllProfitRecords(): Promise<Array<ProfitRecord>>;
    getAnnualProfitRecords(year: string): Promise<Array<ProfitRecord>>;
    getAnnualProfitRecordsByExecutive(executiveUsername: string, year: string): Promise<Array<ProfitRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExecutive(username: string): Promise<ExecutiveCredential>;
    getExecutiveName(executiveUsername: string): Promise<string>;
    getMonthlyProfitRecords(yearMonth: string): Promise<Array<ProfitRecord>>;
    getMonthlyProfitRecordsByExecutive(executiveUsername: string, yearMonth: string): Promise<Array<ProfitRecord>>;
    getProfitRecordsForExecutive(executiveUsername: string): Promise<Array<ProfitRecord>>;
    getRecordsByDay(day: string): Promise<Array<ProfitRecord>>;
    getRecordsByExecutiveByDay(executiveUsername: string, day: string): Promise<Array<ProfitRecord>>;
    getRecordsSortedByAmountReceived(): Promise<Array<ProfitRecord>>;
    getRecordsSortedByDailyTarget(): Promise<Array<ProfitRecord>>;
    getRecordsSortedByDate(): Promise<Array<ProfitRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdminMode(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addExecutive(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExecutive(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExecutive(arg0, arg1, arg2);
            return result;
        }
    }
    async addProfitRecordAsAdmin(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProfitRecordAsAdmin(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProfitRecordAsAdmin(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addProfitRecordAsExecutive(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProfitRecordAsExecutive(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProfitRecordAsExecutive(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateAdmin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateAdmin(arg0, arg1);
            return result;
        }
    }
    async authenticateExecutive(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateExecutive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateExecutive(arg0, arg1);
            return result;
        }
    }
    async changeAdminPassword(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0);
            return result;
        }
    }
    async changeExecutivePassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeExecutivePassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeExecutivePassword(arg0, arg1);
            return result;
        }
    }
    async deleteExecutive(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExecutive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExecutive(arg0);
            return result;
        }
    }
    async deleteProfitRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfitRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfitRecord(arg0);
            return result;
        }
    }
    async getAllExecutives(): Promise<Array<[ExecutiveCredential, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExecutives();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExecutives();
            return result;
        }
    }
    async getAllProfitRecords(): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfitRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfitRecords();
            return result;
        }
    }
    async getAnnualProfitRecords(arg0: string): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnualProfitRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnualProfitRecords(arg0);
            return result;
        }
    }
    async getAnnualProfitRecordsByExecutive(arg0: string, arg1: string): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnualProfitRecordsByExecutive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnualProfitRecordsByExecutive(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExecutive(arg0: string): Promise<ExecutiveCredential> {
        if (this.processError) {
            try {
                const result = await this.actor.getExecutive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExecutive(arg0);
            return result;
        }
    }
    async getExecutiveName(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getExecutiveName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExecutiveName(arg0);
            return result;
        }
    }
    async getMonthlyProfitRecords(arg0: string): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyProfitRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyProfitRecords(arg0);
            return result;
        }
    }
    async getMonthlyProfitRecordsByExecutive(arg0: string, arg1: string): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyProfitRecordsByExecutive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyProfitRecordsByExecutive(arg0, arg1);
            return result;
        }
    }
    async getProfitRecordsForExecutive(arg0: string): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitRecordsForExecutive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitRecordsForExecutive(arg0);
            return result;
        }
    }
    async getRecordsByDay(arg0: string): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordsByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordsByDay(arg0);
            return result;
        }
    }
    async getRecordsByExecutiveByDay(arg0: string, arg1: string): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordsByExecutiveByDay(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordsByExecutiveByDay(arg0, arg1);
            return result;
        }
    }
    async getRecordsSortedByAmountReceived(): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordsSortedByAmountReceived();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordsSortedByAmountReceived();
            return result;
        }
    }
    async getRecordsSortedByDailyTarget(): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordsSortedByDailyTarget();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordsSortedByDailyTarget();
            return result;
        }
    }
    async getRecordsSortedByDate(): Promise<Array<ProfitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordsSortedByDate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordsSortedByDate();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminMode();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
